Repository gymnasium/gymcms, pull requests merged in 2019-10, with the labels that each got.

#130 Add code of conduct
  CODE_OF_CONDUCT.md
  README.md
Labels: enhancement

#131 [release] code of conduct
  CODE_OF_CONDUCT.md
  README.md
Labels: release :tada:

#141 Remove header/footer from takefive pages for testing
  _layouts/take5-raw.html
  take5/catalog-blitz.html
Labels: enhancement

#144 Add logic to sort by publish date
  _data/take5s/GYM-5001.yml
  _data/take5s/GYM-5002.yml
  _data/take5s/GYM-5003.yml
  _data/take5s/GYM-5004.yml
  _data/take5s/GYM-5005.yml
  _data/take5s/GYM-5006.yml
  _data/take5s/GYM-5007.yml
  _data/take5s/GYM-5008.yml
  _data/take5s/GYM-5009.yml
  _data/take5s/GYM-5010.yml
  _data/take5s/GYM-5011.yml
  _data/take5s/GYM-5012.yml
  _data/take5s/GYM-5013.yml
  _data/take5s/GYM-5014.yml
  _data/take5s/GYM-5015.yml
  _data/take5s/GYM-5016.yml
  _data/take5s/GYM-5017.yml
  _data/take5s/GYM-5018.yml
  _data/take5s/GYM-5019.yml
  _data/take5s/GYM-5020.yml
  _includes/take5/recommended-content.html
  _layouts/take5-raw.html
  take5/catalog-blitz.html
  tests/take5/take5-date-lister.html
Labels: Jekyll, Take5

#153 Add template for take5 navigation in /courses
  take5/take5-nav.html
Labels: enhancement

#154 oops - wrong layout
  take5/take5-nav.html
Labels: bug

#155 Wrap nav in comment until golive
  take5/take5-nav.html
Labels: enhancement

#163 [release] clearing take5 warning
  system-status.html
Labels: release :tada:

#166 [release] Transcripts
  take5/gym-5001.md
  take5/gym-5012.md
  take5/gym-5014.md
  take5/gym-5015.md
Labels: release :tada:

#173 [Release] Take 5 Go-live!
  _data/take5s/GYM-5005.yml
  css/take5.css
  home/hero.html
  img/take5/og/gym-5001-og.png
  img/take5/og/gym-5002-og.png
  img/take5/og/gym-5003-og.png
  img/take5/og/gym-5004-og.png
  img/take5/og/gym-5005-og.png
  take5/gym-5001.md
  take5/gym-5002.md
  take5/gym-5003.md
  take5/gym-5004.md
  take5/gym-5005.md
Labels: Take5, release :tada:

#177 [RELEASE] A buncha changes 🍱
  _data/take5s/GYM-5001.yml
  _data/take5s/GYM-5002.yml
  _data/take5s/GYM-5003.yml
  _data/take5s/GYM-5004.yml
  _data/take5s/GYM-5005.yml
  _data/take5s/GYM-5011.yml
  _data/take5s/GYM-5012.yml
  _data/take5s/GYM-5013.yml
  _data/take5s/GYM-5014.yml
  _data/take5s/GYM-5015.yml
  img/take5/posters/gym-5002-hero.jpg
  img/take5/posters/gym-5003-hero.jpg
  take5/gym-5001.md
  take5/gym-5002.md
  take5/gym-5003.md
  take5/gym-5004.md
  take5/gym-5005.md
Labels: Take5, release :tada:

#183 un-hide take5 nav on /courses
  take5/take5-nav.html
Labels: enhancement

#186 [RELEASE] Added "www." to the "heropatterns.com" URL
  _data/take5s/GYM-5002.yml
  take5/gym-5002.md
Labels: Take5, release :tada:

#184 Go live for GYM-5003
  _data/take5s/GYM-5002.yml
  _data/take5s/GYM-5003.yml
Labels: Take5

#188 [staging] GYM-5004 go-live 🥕
  _data/take5s/GYM-5003.yml
  _data/take5s/GYM-5004.yml
Labels: Take5

#189 [RELEASE] 🦑 GYM-5004 aka thursday aka Bobby Bottleservice
  _data/take5s/GYM-5003.yml
  _data/take5s/GYM-5004.yml
Labels: Take5, release :tada:

#191 fix frontmatter
  take5/gym-5004.md
Labels: bug, release :tada:

#192 [RELEASE] Added an improved description to gym-5004
  _data/take5s/GYM-5004.yml
Labels: Take5, enhancement, release :tada:
