Repository gymnasium/gymcms, pull requests merged in 2020-06, with the labels that each got.

#422 Update Jobs page meta
  _layouts/meta.html
  jobs/meta.md
Labels: bug, content

#423 fix permalink path
  webinars/meta/web0004-web-design-is-hard-meta.md
Labels: bug

#424 Style bug updates (various)
  system-status.html
Labels: bug

#425 Wherein Justin eliminates many annoying style bugs 🙏
  _layouts/meta.html
  jobs/meta.md
  system-status.html
  webinars/meta/web0004-web-design-is-hard-meta.md
Labels: release :tada:

#427 Update brand logos
  img/gym-aq-vt-logos/jpg/aquent-a-logo-black.jpg
  img/gym-aq-vt-logos/jpg/aquent-a-logo-orange.jpg
  img/gym-aq-vt-logos/jpg/aquent-logo-white.jpg
  img/gym-aq-vt-logos/jpg/gymnasium-logo-white-lg.jpg
  img/gym-aq-vt-logos/jpg/gymnasium-logo-white-md.jpg
  img/gym-aq-vt-logos/jpg/gymnasium-logo-white-sm.jpg
  img/gym-aq-vt-logos/jpg/vitamin-talent-logo-black.jpg
  img/gym-aq-vt-logos/jpg/vitamin-talent-logo-green.jpg
  img/gym-aq-vt-logos/jpg/vitamin-talent-logo-vt-green.jpg
  img/gym-aq-vt-logos/jpg/vitamin-talent-logo-white.jpg
  img/gym-aq-vt-logos/png/aquent-a-logo-black.png
  img/gym-aq-vt-logos/png/aquent-a-logo-orange.png
  img/gym-aq-vt-logos/png/aquent-a-logo-white.png
  img/gym-aq-vt-logos/png/vitamin-talent-logo-black.png
  img/gym-aq-vt-logos/png/vitamin-talent-logo-green.png
  img/gym-aq-vt-logos/png/vitamin-talent-logo-vt-green.png
  img/gym-aq-vt-logos/png/vitamin-talent-logo-white.png
  img/gym-aq-vt-logos/svg/aquent-a-logo-black.svg
  img/gym-aq-vt-logos/svg/aquent-a-logo-orange.svg
  img/gym-aq-vt-logos/svg/aquent-a-logo-white.svg
  img/gym-aq-vt-logos/svg/vitamin-talent-logo-black.svg
  img/gym-aq-vt-logos/svg/vitamin-talent-logo-green.svg
  img/gym-aq-vt-logos/svg/vitamin-talent-logo-vt-green.svg
  img/gym-aq-vt-logos/svg/vitamin-talent-logo-white.svg
Labels: content

#428 Update hub pages
  hub-pages/career-skills/top.html
  hub-pages/prototyping/bottom.html
  hub-pages/prototyping/top.html
  hub-pages/remote-work/top.html
  hub-pages/ux-design/bottom.html
  hub-pages/ux-design/top.html
  hub-pages/web-development/bottom.html
  hub-pages/web-development/top.html
  img/hub-pages/webinars/featured/decade-of-responsive-web-design-slide.jpg
  img/hub-pages/webinars/featured/prototyping-as-process-paravel-slide.jpg
  img/hub-pages/webinars/featured/remote-work-begin-your-journey-slide.jpg
  img/hub-pages/webinars/featured/remote-work-find-work.jpg
  img/hub-pages/webinars/posters/decade-of-responsive-web-design.jpg
  img/hub-pages/webinars/posters/right-sizing-rapid-prototypes.jpg
  img/hub-pages/webinars/posters/right-sizing-your-rapid-prototypes.jpg
Labels: content

#430 Update in page jump links to jobs section
  jobs/top.html
Labels: bug

#431 [release] squeaky new jobs page!
  _data/webinars/web0006-keeping-up-with-javascript.yml
  _data/webinars/web0007-design-systems-and-creativity.yml
  _data/webinars/web0008-rethinking-full-stack.yml
  _data/webinars/web0009-future-of-web-layout.yml
  _data/webinars/web0011-prototyping-as-process.yml
  _data/webinars/web0012-remote-work.yml
  _data/webinars/web0013-decade-of-responsive-web-design.yml
  _includes/event_slides.html
  _includes/webinar-resources.html
  _layouts/meta.html
  _layouts/webinar.html
  css/webinars.css
  hub-pages/career-skills/top.html
  hub-pages/prototyping/bottom.html
  hub-pages/prototyping/top.html
  hub-pages/remote-work/top.html
  hub-pages/ux-design/bottom.html
  hub-pages/ux-design/top.html
  hub-pages/web-development/bottom.html
  hub-pages/web-development/top.html
  img/gym-aq-vt-logos/jpg/aquent-a-logo-black.jpg
  img/gym-aq-vt-logos/jpg/aquent-a-logo-orange.jpg
  img/gym-aq-vt-logos/jpg/aquent-logo-white.jpg
  img/gym-aq-vt-logos/jpg/gymnasium-logo-white-lg.jpg
  img/gym-aq-vt-logos/jpg/gymnasium-logo-white-md.jpg
  img/gym-aq-vt-logos/jpg/gymnasium-logo-white-sm.jpg
  img/gym-aq-vt-logos/jpg/vitamin-talent-logo-black.jpg
  img/gym-aq-vt-logos/jpg/vitamin-talent-logo-green.jpg
  img/gym-aq-vt-logos/jpg/vitamin-talent-logo-vt-green.jpg
  img/gym-aq-vt-logos/jpg/vitamin-talent-logo-white.jpg
  img/gym-aq-vt-logos/png/aquent-a-logo-black.png
  img/gym-aq-vt-logos/png/aquent-a-logo-orange.png
  img/gym-aq-vt-logos/png/aquent-a-logo-white.png
  img/gym-aq-vt-logos/png/vitamin-talent-logo-black.png
  img/gym-aq-vt-logos/png/vitamin-talent-logo-green.png
  img/gym-aq-vt-logos/png/vitamin-talent-logo-vt-green.png
  img/gym-aq-vt-logos/png/vitamin-talent-logo-white.png
  img/gym-aq-vt-logos/svg/aquent-a-logo-black.svg
  img/gym-aq-vt-logos/svg/aquent-a-logo-orange.svg
  img/gym-aq-vt-logos/svg/aquent-a-logo-white.svg
  img/gym-aq-vt-logos/svg/vitamin-talent-logo-black.svg
  img/gym-aq-vt-logos/svg/vitamin-talent-logo-green.svg
  img/gym-aq-vt-logos/svg/vitamin-talent-logo-vt-green.svg
  img/gym-aq-vt-logos/svg/vitamin-talent-logo-white.svg
  img/hub-pages/webinars/featured/decade-of-responsive-web-design-slide.jpg
  img/hub-pages/webinars/featured/prototyping-as-process-paravel-slide.jpg
  img/hub-pages/webinars/featured/remote-work-begin-your-journey-slide.jpg
  img/hub-pages/webinars/featured/remote-work-find-work.jpg
  img/hub-pages/webinars/posters/decade-of-responsive-web-design.jpg
  img/hub-pages/webinars/posters/right-sizing-rapid-prototypes.jpg
  img/hub-pages/webinars/posters/right-sizing-your-rapid-prototypes.jpg
  jobs/top.html
Labels: release :tada:

#432 Take 5 Marcotte Blitz Week
  _data/take5s/GYM-5031.yml
  _data/take5s/GYM-5032.yml
  _data/take5s/GYM-5033.yml
  _data/take5s/GYM-5034.yml
  _data/take5s/GYM-5035.yml
  _data/take5s/GYM-5036.yml
  css/take5.css
  home/hero.html
  img/take5/og/gym-5032-og.png
  img/take5/og/gym-5033-og.png
  img/take5/og/gym-5034-og.png
  img/take5/og/gym-5035-og.png
  img/take5/og/gym-5036-og.png
  img/take5/posters/gym-5032-hero.jpg
  img/take5/posters/gym-5032.jpg
  img/take5/posters/gym-5033-hero.jpg
  img/take5/posters/gym-5033.jpg
  img/take5/posters/gym-5034-hero.jpg
  img/take5/posters/gym-5034.jpg
  img/take5/posters/gym-5035-hero.jpg
  img/take5/posters/gym-5035.jpg
  img/take5/posters/gym-5036-hero.jpg
  img/take5/posters/gym-5036.jpg
  take5/gym-5032.md
  take5/gym-5033.md
  take5/gym-5034.md
  take5/gym-5035.md
  take5/gym-5036.md
  take5/meta/gym-5032-meta.md
  take5/meta/gym-5033-meta.md
  take5/meta/gym-5034-meta.md
  take5/meta/gym-5035-meta.md
  take5/meta/gym-5036-meta.md
  tests/hero.html
Labels: Take5, content

#434 Take 5 Marcotte blitz update
  _data/take5s/GYM-5032.yml
  _data/take5s/GYM-5033.yml
  _data/take5s/GYM-5034.yml
  _data/take5s/GYM-5035.yml
  _data/take5s/GYM-5036.yml
  _includes/take5/hero-take5-featured.html
  _layouts/take5-raw.html
  css/take5.css
  take5/gym-5032.md
  take5/gym-5033.md
  take5/gym-5034.md
  take5/gym-5035.md
  take5/gym-5036.md
Labels: Take5, content

#435 Take 5 reset prep
  _data/take5s/GYM-5031.yml
  _data/take5s/GYM-5032.yml
  home/hero.html
  tests/hero.html
Labels: Take5, content

#436 Take5 Marcotte blitz live
  _data/take5s/GYM-5031.yml
  _data/take5s/GYM-5032.yml
  _includes/take5/hero-take5-featured.html
  css/hero-take5.css
  home/hero.html
  tests/hero.html
Labels: Take5, content

#438 Custom meta includes for course pages
  Gemfile.lock
  _data/courses/GYM-001.yml
  _data/courses/GYM-003.yml
  _data/courses/GYM-004.yml
  _data/courses/GYM-005.yml
  _data/courses/GYM-006.yml
  _data/courses/GYM-007.yml
  _data/courses/GYM-008.yml
  _data/courses/GYM-009.yml
  _data/courses/GYM-011.yml
  _data/courses/GYM-012.yml
  _data/courses/GYM-013.yml
  _data/courses/GYM-014.yml
  _data/courses/GYM-015.yml
  _data/courses/GYM-100.yml
  _data/courses/GYM-102.yml
  _data/courses/GYM-103.yml
  _data/courses/GYM-104.yml
  _data/courses/GYM-105.yml
  _data/courses/GYM-106.yml
  _data/courses/GYM-107.yml
  _data/courses/GYM-108.yml
  _data/courses/GYM-109.yml
  _data/take5s/GYM-5003.yml
  _layouts/meta.html
  courses/GYM-001/gym-001-meta.md
  courses/GYM-003/gym-003-meta.md
  courses/GYM-004/gym-004-meta.md
  courses/GYM-005/gym-005-meta.md
  courses/GYM-006/gym-006-meta.md
  courses/GYM-007/gym-007-meta.md
  courses/GYM-008/gym-008-meta.md
  courses/GYM-009/gym-009-meta.md
  courses/GYM-011/gym-011-meta.md
  courses/GYM-012/gym-012-meta.md
  courses/GYM-013/gym-013-meta.md
  courses/GYM-014/gym-014-meta.md
  courses/GYM-015/gym-015-meta.md
  courses/GYM-016/gym-016-meta.md
  courses/GYM-100/gym-100-meta.md
  courses/GYM-102/gym-102-meta.md
  courses/GYM-103/gym-103-meta.md
  courses/GYM-104/gym-104-meta.md
  courses/GYM-105/gym-105-meta.md
  courses/GYM-106/gym-106-meta.md
  courses/GYM-107/gym-107-meta.md
  courses/GYM-108/gym-108-meta.md
  courses/GYM-109/gym-109-meta.md
  tests/catalog/lister.html
  tests/catalog/metas.html
Labels: Jekyll, enhancement

#439 Take 5 Marcotte Blitz Day 2
  _data/take5s/GYM-5032.yml
  _data/take5s/GYM-5033.yml
Labels: Take5, content

#440 [release] Marcotte Blitz day 2 and course meta!
  Gemfile.lock
  _data/courses/GYM-001.yml
  _data/courses/GYM-003.yml
  _data/courses/GYM-004.yml
  _data/courses/GYM-005.yml
  _data/courses/GYM-006.yml
  _data/courses/GYM-007.yml
  _data/courses/GYM-008.yml
  _data/courses/GYM-009.yml
  _data/courses/GYM-011.yml
  _data/courses/GYM-012.yml
  _data/courses/GYM-013.yml
  _data/courses/GYM-014.yml
  _data/courses/GYM-015.yml
  _data/courses/GYM-100.yml
  _data/courses/GYM-102.yml
  _data/courses/GYM-103.yml
  _data/courses/GYM-104.yml
  _data/courses/GYM-105.yml
  _data/courses/GYM-106.yml
  _data/courses/GYM-107.yml
  _data/courses/GYM-108.yml
  _data/courses/GYM-109.yml
  _data/take5s/GYM-5003.yml
  _data/take5s/GYM-5032.yml
  _data/take5s/GYM-5033.yml
  _layouts/meta.html
  courses/GYM-001/gym-001-meta.md
  courses/GYM-003/gym-003-meta.md
  courses/GYM-004/gym-004-meta.md
  courses/GYM-005/gym-005-meta.md
  courses/GYM-006/gym-006-meta.md
  courses/GYM-007/gym-007-meta.md
  courses/GYM-008/gym-008-meta.md
  courses/GYM-009/gym-009-meta.md
  courses/GYM-011/gym-011-meta.md
  courses/GYM-012/gym-012-meta.md
  courses/GYM-013/gym-013-meta.md
  courses/GYM-014/gym-014-meta.md
  courses/GYM-015/gym-015-meta.md
  courses/GYM-016/gym-016-meta.md
  courses/GYM-100/gym-100-meta.md
  courses/GYM-102/gym-102-meta.md
  courses/GYM-103/gym-103-meta.md
  courses/GYM-104/gym-104-meta.md
  courses/GYM-105/gym-105-meta.md
  courses/GYM-106/gym-106-meta.md
  courses/GYM-107/gym-107-meta.md
  courses/GYM-108/gym-108-meta.md
  courses/GYM-109/gym-109-meta.md
  tests/catalog/lister.html
  tests/catalog/metas.html
Labels: Take5, release :tada:

#441 Update Twitch embed
  _includes/hero-livecoding.html
  tests/hero.html
Labels: bug

#442 Take 5 hero update
  css/hero-take5.css
  img/take5/posters/gym-5033-hero.jpg
  img/take5/posters/gym-5033.jpg
Labels: bug

#443 Take 5 Marcotte Blitz Day 3
  _data/take5s/GYM-5033.yml
  _data/take5s/GYM-5034.yml
  _includes/hero-livecoding.html
  home/hero.html
  tests/hero.html
Labels: Take5, content

#445 fix rendering glitch on hub pages
  hub-pages/career-skills/test.html
  hub-pages/prototyping/test.html
  hub-pages/remote-work/test.html
  hub-pages/ux-design/test.html
  hub-pages/web-development/test.html
  jobs/test.html
Labels: Jekyll, bug

#448 Take 5 Marcotte Blitz Day 4
  _data/take5s/GYM-5034.yml
  _data/take5s/GYM-5035.yml
Labels: Take5, content

#450 Take 5 Marcotte Blitz Day 5
  _data/take5s/GYM-5035.yml
  _data/take5s/GYM-5036.yml
Labels: Take5, content

#452 Take 5 campaign hero swap
  _data/take5s/GYM-5036.yml
  home/hero.html
  tests/hero.html
Labels: content

#454 Update Take 5 featured state
  _data/take5s/GYM-5033.yml
  _data/take5s/GYM-5034.yml
  _data/take5s/GYM-5035.yml
Labels: bug
