Repository gymnasium/gymcms, pull requests merged in 2020-05, with the labels that each got.

#399 Update Designing for Good hero
  _includes/hero-dfg-2020.html
  css/hero-dfg-2020.css
  css/hero-dfg-2020/hero-dfg-2020-heart.css
  css/hero-dfg-2020/hero-dfg-2020-people.css
  home/img/hero-dfg-2020/designing-for-good-2020-hero-1440w.jpg
  home/img/hero-dfg-2020/designing-for-good-2020-hero-2000w.jpg
  home/img/hero-dfg-2020/designing-for-good-2020-hero-720w.jpg
  home/img/hero-dfg-2020/designing-for-good-2020-hero-heart-1440w.jpg
  home/img/hero-dfg-2020/designing-for-good-2020-hero-heart-2000w.jpg
  home/img/hero-dfg-2020/designing-for-good-2020-hero-heart-720w.jpg
  home/img/hero-dfg-2020/designing-for-good-2020-hero-people-1440w.jpg
  home/img/hero-dfg-2020/designing-for-good-2020-hero-people-2000w.jpg
  home/img/hero-dfg-2020/designing-for-good-2020-hero-people-720w.jpg
Labels: content

#401 Update remote work content
  footer.html
  hub-pages/remote-work/meta.md
  tests/collections.html
Labels: content

#402 [release] remote work meta updates
  footer.html
  hub-pages/remote-work/meta.md
  tests/collections.html
Labels: release :tada:

#403 Update text color and contrast ratio
  css/hub-pages.css
Labels: enhancement

#405 Update webinar short description
  _data/webinars/web0013-decade-of-responsive-web-design.yml
Labels: content

#408 Update webinar and remote jobs content
  _data/bios/emarcotte.yml
  _data/webinars/web0013-decade-of-responsive-web-design.yml
  hub-pages/remote-work/bottom.html
  hub-pages/remote-work/top.html
Labels: content

#411 Decade of RWD webinar hero
  _includes/hero-webinar-05-2020.html
  css/hero-webinar-05-2020.css
  home/hero.html
  home/img/hero-webinar-05-2020/ala-306-rwd-2010-20-720w.png
  home/img/hero-webinar-05-2020/ethanmarcotte-2020-1080w.jpg
  tests/hero.html
Labels: enhancement

#412 Decade of RWD webinar hero (#411)
  _includes/hero-webinar-05-2020.html
  css/hero-webinar-05-2020.css
  home/hero.html
  home/img/hero-webinar-05-2020/ala-306-rwd-2010-20-720w.png
  home/img/hero-webinar-05-2020/ethanmarcotte-2020-1080w.jpg
  tests/hero.html
Labels: enhancement

#413 Swap hero and webinar recording prep
  _data/webinars/web0013-decade-of-responsive-web-design.yml
  home/hero.html
  tests/hero.html
Labels: content

#414 Swap hero and webinar recording prep (#413)
  _data/webinars/web0013-decade-of-responsive-web-design.yml
  home/hero.html
  tests/hero.html
Labels: content

#415 Update webinar states
  _includes/hero-webinar-05-2020.html
  _layouts/webinar.html
  css/hero-webinar-05-2020.css
  css/webinars.css
  webinars/webinars.html
Labels: content

#416 Update webinar states (#415)
  _includes/hero-webinar-05-2020.html
  _layouts/webinar.html
  css/hero-webinar-05-2020.css
  css/webinars.css
  webinars/webinars.html
Labels: content

#418 Update webinars available soon text style
  css/webinars.css
  webinars/webinars.html
Labels: bug, content

#419 Update webinars available soon text style (#418)
  css/webinars.css
  webinars/webinars.html
Labels: bug, content

#420 Webinar recording available
  _data/webinars/web0013-decade-of-responsive-web-design.yml
  _includes/hero-webinar-05-2020.html
  css/hero-webinar-05-2020.css
  home/hero.html
  tests/hero.html
Labels: content, enhancement

#421 Webinar recording available
  _data/webinars/web0013-decade-of-responsive-web-design.yml
  _includes/hero-webinar-05-2020.html
  css/hero-webinar-05-2020.css
  home/hero.html
  tests/hero.html
Labels: release :tada:
