Repository gymnasium/gymcms, pull requests merged in 2020-07, with the labels that each got.

#456 Fix hero small screen layout
  _includes/hero-take5-campaign.html
  css/hero-bbd-2018.css
  css/hero-blue-beanie.css
  css/hero-dfg-2019.css
  css/hero-dfg-2020.css
  css/hero-dfg.css
  css/hero-fwl-live-event.css
  css/hero-gym-014.css
  css/hero-gym-015.css
  css/hero-live-coding.css
  css/hero-live-event.css
  css/hero-net-neutrality.css
  css/hero-promo-badges.css
  css/hero-promo-rdf.css
  css/hero-take5-campaign.css
  css/hero-take5.css
  css/hero-webinar-03-2020.css
  css/hero-webinar-05-2020.css
  css/hero-webinar-12-2018.css
Labels: bug

#457 Remove redirection script from cms test pages
  _layouts/test-footer-minimal.html
  _layouts/test-home-minimal.html
  _layouts/test-home.html
Labels: bug

#458 GYM-016 Meta Update
  _data/courses/GYM-016.yml
  _layouts/meta-gym-016.html
  courses/GYM-016/gym-016-meta.md
  img/badges-artwork/gym-016-badge.png
  img/course-artwork/png/gym-016.png
  img/course-artwork/svg/gym-016.svg
  img/social/courses/gym-016-social.png
Labels: content

#459 LMS Style Update
  system-status.html
Labels: bug, content

#460 Add GYM-016 Hero
  _includes/hero-gym-016.html
  css/hero-gym-016.css
  home/hero.html
  img/badges-artwork/png/gym-001-badge.png
  img/badges-artwork/png/gym-003-badge.png
  img/badges-artwork/png/gym-004-badge.png
  img/badges-artwork/png/gym-005-badge.png
  img/badges-artwork/png/gym-006-badge.png
  img/badges-artwork/png/gym-007-badge.png
  img/badges-artwork/png/gym-008-badge.png
  img/badges-artwork/png/gym-009-badge.png
  img/badges-artwork/png/gym-011-badge.png
  img/badges-artwork/png/gym-012-badge.png
  img/badges-artwork/png/gym-013-badge.png
  img/badges-artwork/png/gym-014-badge.png
  img/badges-artwork/png/gym-015-badge.png
  img/badges-artwork/png/gym-016-badge.png
  img/badges-artwork/svg/gym-016-badge.svg
  tests/hero.html
Labels: content

#461 [Release] Designing Accessible and Responsive Websites without redirect plus meta and style
  _data/courses/GYM-016.yml
  _data/courses/GYM-106.yml
  _includes/hero-gym-016.html
  _layouts/meta-gym-016.html
  _layouts/test-footer-minimal.html
  _layouts/test-home-minimal.html
  _layouts/test-home.html
  courses/GYM-016/gym-016-meta.md
  css/hero-gym-016.css
  home/hero.html
  img/badges-artwork/png/gym-001-badge.png
  img/badges-artwork/png/gym-003-badge.png
  img/badges-artwork/png/gym-004-badge.png
  img/badges-artwork/png/gym-005-badge.png
  img/badges-artwork/png/gym-006-badge.png
  img/badges-artwork/png/gym-007-badge.png
  img/badges-artwork/png/gym-008-badge.png
  img/badges-artwork/png/gym-009-badge.png
  img/badges-artwork/png/gym-011-badge.png
  img/badges-artwork/png/gym-012-badge.png
  img/badges-artwork/png/gym-013-badge.png
  img/badges-artwork/png/gym-014-badge.png
  img/badges-artwork/png/gym-015-badge.png
  img/badges-artwork/png/gym-016-badge.png
  img/badges-artwork/svg/gym-016-badge.svg
  img/course-artwork/png/gym-016.png
  img/course-artwork/svg/gym-016.svg
  img/social/courses/gym-016-social.png
  system-status.html
  tests/hero.html
Labels: release :tada:

#462 GYM-016 Hero Update
  css/hero-gym-016.css
Labels: content

#464 Create a featured courses "feed"
  _data/bios/agustafson.yml
  _data/bios/bfrost.yml
  _data/bios/bharned.yml
  _data/bios/dbuckner.yml
  _data/bios/dmall.yml
  _data/bios/dporter.yml
  _data/bios/drupert.yml
  _data/bios/emarcotte.yml
  _data/bios/emeyer.yml
  _data/bios/eyoung.yml
  _data/bios/ghodgkinson.yml
  _data/bios/groberts.yml
  _data/bios/honeill.yml
  _data/bios/jausura.yml
  _data/bios/jbantjes.yml
  _data/bios/jhodgins.yml
  _data/bios/jkramer.yml
  _data/bios/josborn.yml
  _data/bios/jpamental.yml
  _data/bios/jwebb.yml
  _data/bios/jyoung.yml
  _data/bios/jzeldman.yml
  _data/bios/kchisholm.yml
  _data/bios/kmcgrane.yml
  _data/bios/kpeters.yml
  _data/bios/randrew.yml
  _data/bios/rbanfield.yml
  _data/bios/shay.yml
  _data/bios/sshepherd.yml
  _data/bios/tsellon.yml
  _data/bios/tsingleton.yml
  _data/bios/tslate.yml
  _data/courses/GYM-001.yml
  _data/courses/GYM-003.yml
  _data/courses/GYM-004.yml
  _data/courses/GYM-005.yml
  _data/courses/GYM-006.yml
  _data/courses/GYM-007.yml
  _data/courses/GYM-008.yml
  _data/courses/GYM-009.yml
  _data/courses/GYM-011.yml
  _data/courses/GYM-012.yml
  _data/courses/GYM-013.yml
  _data/courses/GYM-014.yml
  _data/courses/GYM-015.yml
  _data/courses/GYM-016.yml
  _data/courses/GYM-100.yml
  _data/courses/GYM-102.yml
  _data/courses/GYM-103.yml
  _data/courses/GYM-104.yml
  _data/courses/GYM-105.yml
  _data/courses/GYM-106.yml
  _data/courses/GYM-107.yml
  _data/courses/GYM-108.yml
  _data/courses/GYM-109.yml
  _layouts/raw.html
  feeds/featured-courses.html
  tests/featurer.html
Labels: enhancement
