Repository gymnasium/gymcms, pull requests merged in 2020-03, with the labels that each got.

#347 Update webinar reg form functionality
  _layouts/webinar.html
Labels: bug

#352 Add GYM-5030 content
  _data/take5s/GYM-5029.yml
  _data/take5s/GYM-5030.yml
  img/take5/og/gym-5030-og.png
  img/take5/posters/gym-5030-hero.jpg
  img/take5/posters/gym-5030.jpg
  take5/gym-5030.md
  take5/meta/gym-5030-meta.md
Labels: Take5, content

#356 [release] Webinars + take 5
  _data/take5s/GYM-5029.yml
  _data/take5s/GYM-5030.yml
  _data/webinars/web0005-state-of-responsive-web-design.yml
  _includes/take5/test-bottom.html
  footer.html
  hub-pages/career-skills/bottom.html
  hub-pages/prototyping/bottom.html
  hub-pages/prototyping/top.html
  hub-pages/ux-design/bottom.html
  hub-pages/ux-design/top.html
  hub-pages/web-development/bottom.html
  hub-pages/web-development/top.html
  img/hub-pages/webinars/posters/state-of-responsive-web-design.jpg
  img/take5/og/gym-5030-og.png
  img/take5/posters/gym-5030-hero.jpg
  img/take5/posters/gym-5030.jpg
  take5/gym-5030.md
  take5/meta/gym-5030-meta.md
  webinars/meta/web0005-state-of-responsive-web-design-meta.md
  webinars/web0005-state-of-responsive-web-design.md
Labels: Take5, release :tada:

#363 [release] URL fixes for that one webinar
  _layouts/meta.html
  tests/webinars-test.html
  webinars/webinars.html
Labels: release :tada:

#369 Can it work for you? ➡️ Make it work for you!
  _includes/hero-webinar-03-2020.html
  css/hero-webinar-03-2020.css
Labels: enhancement

#370 [release] can it / make it / do it / makes us / stronger / better / faster / robots 🤖
  _includes/hero-webinar-03-2020.html
  css/hero-webinar-03-2020.css
  tests/collections.html
Labels: release :tada:

#371 Add GYM-5031 content
  _data/take5s/GYM-5030.yml
  _data/take5s/GYM-5031.yml
  img/take5/og/gym-5031-og.png
  img/take5/posters/gym-5031-hero.jpg
  img/take5/posters/gym-5031.jpg
  take5/gym-5031.md
  take5/meta/gym-5031-meta.md
Labels: Take5, content

#372 Feature GYM-5030
  _data/take5s/GYM-5030.yml
Labels: Take5, content

#373 Update webinar state
  _data/webinars/web0012-remote-work.yml
  _layouts/webinar.html
Labels: Jekyll, content

#374 Update home page hero
  home/hero.html
  tests/hero.html
Labels: content

#376 Update webinar logic
  _layouts/webinar.html
Labels: content

#378 Fix webinar logic
  _layouts/webinar.html
Labels: content

#379 Update webinar content
  _data/webinars/web0012-remote-work.yml
  home/hero.html
  tests/hero.html
  webinars/webinars.html
Labels: content

#381 Prep GYM-5031 for release
  _data/take5s/GYM-5030.yml
  _data/take5s/GYM-5031.yml
  home/hero.html
  take5/gym-5031.md
  tests/hero.html
Labels: Take5, content

#383 [release] take5, and fixing the metas
  _data/take5s/GYM-5030.yml
  _data/take5s/GYM-5031.yml
  _includes/take5/hero-take5-featured.html
  _layouts/meta.html
  css/hero-take5.css
  home/hero.html
  hub-pages/career-skills/meta.md
  hub-pages/prototyping/meta.md
  hub-pages/remote-work/bottom.html
  hub-pages/remote-work/meta.md
  hub-pages/remote-work/test.html
  hub-pages/remote-work/top.html
  hub-pages/ux-design/meta.md
  hub-pages/web-development/meta.md
  take5/gym-5031.md
  tests/collections.html
  tests/hero.html
Labels: Take5
