Repository gymnasium/gymcms, pull requests merged in 2020-04, with the labels that each got.

#384 Add Designing for Good 2020 hero
  _includes/hero-dfg-2020.html
  css/hero-dfg-2020/hero-dfg-2020-heart.css
  css/hero-dfg-2020/hero-dfg-2020-people.css
  css/hero-dfg-2020/hero-dfg-2020.css
  home/hero.html
  home/img/hero-dfg-2020/designing-for-good-2020-hero-heart-1440w.jpg
  home/img/hero-dfg-2020/designing-for-good-2020-hero-heart-2000w.jpg
  home/img/hero-dfg-2020/designing-for-good-2020-hero-heart-720w.jpg
  home/img/hero-dfg-2020/designing-for-good-2020-hero-people-1440w.jpg
  home/img/hero-dfg-2020/designing-for-good-2020-hero-people-2000w.jpg
  home/img/hero-dfg-2020/designing-for-good-2020-hero-people-720w.jpg
  tests/hero.html
Labels: content

#386 [release] performance improvements
  _includes/hero-dfg-2020.html
  css/hero-dfg-2020/hero-dfg-2020-heart.css
  css/hero-dfg-2020/hero-dfg-2020-people.css
  css/hero-dfg-2020/hero-dfg-2020.css
  home/hero.html
  home/img/hero-dfg-2020/designing-for-good-2020-hero-heart-1440w.jpg
  home/img/hero-dfg-2020/designing-for-good-2020-hero-heart-2000w.jpg
  home/img/hero-dfg-2020/designing-for-good-2020-hero-heart-720w.jpg
  home/img/hero-dfg-2020/designing-for-good-2020-hero-people-1440w.jpg
  home/img/hero-dfg-2020/designing-for-good-2020-hero-people-2000w.jpg
  home/img/hero-dfg-2020/designing-for-good-2020-hero-people-720w.jpg
  tests/hero.html
Labels: release :tada:

#387 Update footer social plus improvements
  footer.html
  img/brand/png/gymnasium-logo-white-4x.png
  img/brand/svg/gymnasium-logo-white.svg
  img/social/icons/icon-instagram.svg
  img/social/icons/icon-twitter-4x.png
  img/social/icons/png/icon-facebook-4x.png
  img/social/icons/png/icon-github-4x.png
  img/social/icons/png/icon-instagram-4x.png
  img/social/icons/png/icon-linkedin-4x.png
  img/social/icons/png/icon-medium-4x.png
  img/social/icons/png/icon-twitter-4x.png
  img/social/icons/png/icon-youtube-4x.png
  img/social/icons/svg/icon-facebook.svg
  img/social/icons/svg/icon-github.svg
  img/social/icons/svg/icon-instagram.svg
  img/social/icons/svg/icon-linkedin.svg
  img/social/icons/svg/icon-medium.svg
  img/social/icons/svg/icon-twitter.svg
  img/social/icons/svg/icon-youtube.svg
Labels: content

#390 Remote work hub page
  css/hub-pages.css
  hub-pages/remote-work/bottom.html
  hub-pages/remote-work/meta.md
  hub-pages/remote-work/top.html
  img/hub-pages/og/remote-work-resources-og.png
  img/hub-pages/remote-work/featured/find-remote-work.jpg
  img/hub-pages/remote-work/featured/vt-salary-guide-2020.jpg
  img/hub-pages/webinars/featured/prototyping-as-process-paraval-slide.jpg
  img/hub-pages/webinars/featured/remote-work-find-work.jpg
  tests/collections.html
Labels: content

#391 Update jobs page content
  jobs.md
Labels: content

#392 Update jobs page content layout
  css/hub-pages.css
  img/hub-pages/remote-work/featured/vt-salary-guide-2020.jpg
  img/jobs/og/jobs-og.png
  img/social/collections/ux-design-social.png
  jobs/bottom.html
  jobs/meta.md
  jobs/test.html
  jobs/top.html
Labels: content

#393 Update jobs nav jump link
  jobs/top.html
Labels: content

#394 Update remote work content
  hub-pages/remote-work/bottom.html
Labels: content

#395 Improve Jobs and Remote Work resources accessibility
  hub-pages/remote-work/top.html
  img/hub-pages/remote-work/featured/find-work.jpg
  jobs/top.html
Labels: content

#396 Update footer layout and accessibility
  css/footer.css
  footer.html
Labels: enhancement

#397 Fix Forum related display of fonts and footer layout
  css/footer.css
  footer.html
Labels: enhancement
