Repository gymnasium/gymcms, pull requests merged in 2020-11, with the labels that each got.

#515 Add GYM-5045 content
  _data/take5s/GYM-5044.yml
  _data/take5s/GYM-5045.yml
  img/take5/og/gym-5045-og.png
  img/take5/posters/gym-5045-hero.jpg
  img/take5/posters/gym-5045.jpg
  take5/gym-5044.md
  take5/gym-5045.md
  take5/meta/gym-5045-meta.md
Labels: Take5, content

#517 Update GYM-5045
  _data/take5s/GYM-5045.yml
  take5/gym-5045.md
Labels: Take5, content

#516 [Release] New Take 5 and Tagline
  _data/take5s/GYM-5044.yml
  _data/take5s/GYM-5045.yml
  footer.html
  home/featured-courses.html
  img/take5/og/gym-5045-og.png
  img/take5/posters/gym-5045-hero.jpg
  img/take5/posters/gym-5045.jpg
  take5/gym-5044.md
  take5/gym-5045.md
  take5/meta/gym-5045-meta.md
Labels: content, release :tada:

#518 Add class to final exam messaging buttons for hawthorn fix
  final-exam-modal-top.html
  final-exam-modal.html
Labels: bug

#520 Add GYM-5046 content
  _data/take5s/GYM-5045.yml
  _data/take5s/GYM-5046.yml
  img/take5/og/gym-5046-og.png
  img/take5/posters/gym-5046-hero.jpg
  img/take5/posters/gym-5046.jpg
  take5/gym-5046.md
  take5/meta/gym-5046-meta.md
Labels: Take5, content

#521 [Release] Add new Take 5 and update link style
  _data/take5s/GYM-5045.yml
  _data/take5s/GYM-5046.yml
  css/privacy-policy.css
  final-exam-modal-top.html
  final-exam-modal.html
  img/take5/og/gym-5046-og.png
  img/take5/posters/gym-5046-hero.jpg
  img/take5/posters/gym-5046.jpg
  take5/gym-5046.md
  take5/meta/gym-5046-meta.md
Labels: release :tada:

#523 Revert "Revert "[Release] Add new Take 5 and update link style""
  _data/take5s/GYM-5045.yml
  _data/take5s/GYM-5046.yml
  css/privacy-policy.css
  final-exam-modal-top.html
  final-exam-modal.html
  img/take5/og/gym-5046-og.png
  img/take5/posters/gym-5046-hero.jpg
  img/take5/posters/gym-5046.jpg
  take5/gym-5046.md
  take5/meta/gym-5046-meta.md
Labels: Take5, release :tada:

#524 Update a11y link style
  system-status.html
Labels: bug

#528 Add email related artwork
  img/email/brand/gymnasium-logo.gif
  img/email/social/facebook-icon.gif
  img/email/social/github-icon.gif
  img/email/social/instagram-icon.gif
  img/email/social/linkedin-icon.gif
  img/email/social/medium-icon.gif
  img/email/social/twitter-icon.gif
  img/email/social/youtube-play-icon.gif
Labels: content

#531 Update password reset form style
  system-status.html
Labels: bug

#533 Update GYM-5047 content
  _data/take5s/GYM-5046.yml
  _data/take5s/GYM-5047.yml
Labels: Take5, content

#532 Update a11y link style for Hawthorn
  system-status.html
Labels: bug

#534 Update various link styles
  css/privacy-policy.css
  privacy-policy.html
  system-status.html
Labels: bug

#535 [Release] Add GYM-5047 with form and link style updates
  _data/take5s/GYM-5046.yml
  _data/take5s/GYM-5047.yml
  css/privacy-policy.css
  img/take5/og/gym-5046-og.png
  img/take5/og/gym-5047-og.png
  img/take5/posters/gym-5047-hero.jpg
  img/take5/posters/gym-5047.jpg
  privacy-policy.html
  system-status.html
  take5/gym-5047.md
  take5/meta/gym-5047-meta.md
Labels: release :tada:

#536 Update final exam punctuation
  final-exam-modal-top.html
  final-exam-modal.html
Labels: content

#538 Add GYM-5048 content
  _data/take5s/GYM-5047.yml
  _data/take5s/GYM-5048.yml
  img/take5/og/gym-5048-og.png
  img/take5/posters/gym-5048-hero.jpg
  img/take5/posters/gym-5048.jpg
  take5/gym-5048.md
  take5/meta/gym-5048-meta.md
Labels: Take5, content

#539 [Release] Take 5 turns 48
  _data/take5s/GYM-5047.yml
  _data/take5s/GYM-5048.yml
  img/take5/og/gym-5048-og.png
  img/take5/posters/gym-5048-hero.jpg
  img/take5/posters/gym-5048.jpg
  take5/gym-5048.md
  take5/meta/gym-5048-meta.md
Labels: release :tada:

#540 Update sidebar content
  sidebar-generic.html
  upcoming-courses.html
Labels: content

#541 Absolute URLs for sidebar links and assets based on environment
  css/static-main-content.css
  css/static-sidebar-content.css
  sidebar-generic.html
  sidebar-login.html
  sidebar-register.html
  upcoming-courses.html
Labels: enhancement

#542 Update GYM-5048 content
  _data/take5s/GYM-5047.yml
  _data/take5s/GYM-5048.yml
Labels: Take5, content

#543 [Release] Add GYM-5048 and update sidebar content plus Hawthorn links
  _data/take5s/GYM-5047.yml
  _data/take5s/GYM-5048.yml
  css/static-main-content.css
  css/static-sidebar-content.css
  sidebar-generic.html
  sidebar-login.html
  sidebar-register.html
  upcoming-courses.html
Labels: release :tada:

#544 Update privacy policy
  privacy-policy.html
Labels: content

#545 Add 2020 Blue Beanie Day hero
  _includes/hero-bbd-2020.html
  _layouts/test-home-minimal.html
  css/hero-bbd-2020.css
  home/hero.html
  home/img/hero-bbd-2020/blue-beanie-day-gang-2020-1280w.png
  home/img/hero-bbd-2020/blue-beanie-day-gang-2020-720w.png
  tests/hero.html
Labels: content, enhancement
