Repository gymnasium/gymcms, pull requests merged in 2021-12, with the labels that each got.

#695 [Feature/Bug fix]: Migrate external vendor files to gymcms
  _includes/partials/footer.html
  _includes/partials/meta/tags.html
  _includes/partials/test-top.html
  css/main.scss
  css/vendor/bootstrap.min.css
  js/vendor/bootstrap.min.js
  js/vendor/cookiebanner.js
  js/vendor/jquery.validate.min.js
  js/vendor/prism.min.js
Labels: bug, enhancement

#703 Update home page hero campaign
  _data/hero.yml
  css/hero-take5-campaign.scss
Labels: content, CSS

#704 [Release]: Take 5 this New Year!
  _data/hero.yml
  css/hero-take5-campaign.scss
Labels: release :tada:
