Repository gymnasium/gymcms, pull requests merged in 2021-09, with the labels that each got.

#669 Update Gymnasium descriptions
  _includes/home/featured-courses.html
  courses/meta.md
  home/meta.md
Labels: content

#670 [Release]: Updated language and script things 🤖
  _includes/home/featured-courses.html
  _includes/partials/meta/tags.html
  _sass/_theme-hacks.scss
  courses/meta.md
  home/meta.md
  js/gymnasium.js
  partials/final-exam-modal-top.html
  partials/final-exam-modal.html
Labels: release :tada:

#671 [Feature] Add disclaimer to account deletion text
  js/gymnasium.js
  partials/account-deletion.html
Labels: enhancement
