Repository gymnasium/gymcms, pull requests merged in 2021-07, with the labels that each got.

#639 Designing for Good 2021 Hero
  _data/hero.yml
  _includes/hero-dfg-2021.html
  _sass/_variables.scss
  css/hero-dfg-2021.scss
  home/img/hero-dfg-2021/designing-for-good-2021-hero-1440w.jpg
  home/img/hero-dfg-2021/designing-for-good-2021-hero-2000w.jpg
  home/img/hero-dfg-2021/designing-for-good-2021-hero-720w.jpg
Labels: content

#649 Tidy hero includes
  _includes/heros/hero-bbd-2018.html
  _includes/heros/hero-bbd-2020-accessibility.html
  _includes/heros/hero-bbd-2020-gym-016.html
  _includes/heros/hero-bbd-2020-gym-107.html
  _includes/heros/hero-bbd-2020.html
  _includes/heros/hero-collections.html
  _includes/heros/hero-design-systems.html
  _includes/heros/hero-dfg-2019.html
  _includes/heros/hero-dfg-2020.html
  _includes/heros/hero-dfg-2021.html
  _includes/heros/hero-fwl-live-event.html
  _includes/heros/hero-gym-005.html
  _includes/heros/hero-gym-014.html
  _includes/heros/hero-gym-015.html
  _includes/heros/hero-gym-016.html
  _includes/heros/hero-livecoding.html
  _includes/heros/hero-promo-badges.html
  _includes/heros/hero-promo-rdf.html
  _includes/heros/hero-take5-campaign.html
  _includes/heros/hero-ux-design-collection.html
  _includes/heros/hero-webinar-03-2020-video.html
  _includes/heros/hero-webinar-03-2020.html
  _includes/heros/hero-webinar-05-2019-video.html
  _includes/heros/hero-webinar-05-2019.html
  _includes/heros/hero-webinar-05-2020.html
  _includes/heros/hero-webinar-12-2018-video.html
  _includes/heros/hero-webinar-12-2018.html
  _layouts/hero.html
  _layouts/wrapper-home.html
  tests/hero/hero-test-auth.html
  tests/hero/hero-test-index.html
  tests/hero/hero-test-live-coding.html
  tests/hero/hero-test-public.html
Labels: enhancement

#648 [Release]: deploy impressum, tidy heros, dev prototype page
  Gemfile.lock
  _includes/heros/hero-bbd-2018.html
  _includes/heros/hero-bbd-2020-accessibility.html
  _includes/heros/hero-bbd-2020-gym-016.html
  _includes/heros/hero-bbd-2020-gym-107.html
  _includes/heros/hero-bbd-2020.html
  _includes/heros/hero-collections.html
  _includes/heros/hero-design-systems.html
  _includes/heros/hero-dfg-2019.html
  _includes/heros/hero-dfg-2020.html
  _includes/heros/hero-dfg-2021.html
  _includes/heros/hero-fwl-live-event.html
  _includes/heros/hero-gym-005.html
  _includes/heros/hero-gym-014.html
  _includes/heros/hero-gym-015.html
  _includes/heros/hero-gym-016.html
  _includes/heros/hero-livecoding.html
  _includes/heros/hero-promo-badges.html
  _includes/heros/hero-promo-rdf.html
  _includes/heros/hero-take5-campaign.html
  _includes/heros/hero-ux-design-collection.html
  _includes/heros/hero-webinar-03-2020-video.html
  _includes/heros/hero-webinar-03-2020.html
  _includes/heros/hero-webinar-05-2019-video.html
  _includes/heros/hero-webinar-05-2019.html
  _includes/heros/hero-webinar-05-2020.html
  _includes/heros/hero-webinar-12-2018-video.html
  _includes/heros/hero-webinar-12-2018.html
  _includes/partials/footer.html
  _layouts/hero.html
  _layouts/wrapper-home.html
  dev/index-auth.html
  dev/index.html
  dev/prototypes/courses/comp-1.html
  dev/prototypes/courses/css/main.scss
  img/as-seen-in/fastco.png
  img/as-seen-in/forbes.png
  img/as-seen-in/fox-business.png
  img/as-seen-in/inc.png
  img/as-seen-in/le-monde-fr.png
  tests/hero/hero-test-auth.html
  tests/hero/hero-test-index.html
  tests/hero/hero-test-live-coding.html
  tests/hero/hero-test-public.html
Labels: release :tada:
