Repository gymnasium/gymcms, pull requests merged in 2021-11, with the labels that each got.

#685 [Release]: Update Take 5 hero CSS animation
  _sass/_animations.scss
  css/hero-take5-campaign.scss
Labels: release :tada:

#687 [Release]: Update courses prototype with bug fix and tweak
  dev/prototypes/courses/css/main.scss
Labels: release :tada:

#690 Update Bootstrap reset
  _sass/_mixins.scss
Labels: enhancement, CSS

#692 [Feature]: Establish a main.scss, eliminate inline CSS/theme hacks, move footer to main.scss
  _includes/inline.scss
  _includes/partials/footer.html
  _includes/partials/meta/tags.html
  _layouts/default.html
  css/footer.scss
  css/main.scss
Labels: enhancement

#689 [Release]: Courses prototype updates with font fixes
  _data/take5/GYM-5042.yml
  _includes/inline.scss
  _includes/partials/footer.html
  _includes/partials/meta/tags.html
  _layouts/default.html
  _sass/_mixins.scss
  _sass/_theme-hacks.scss
  _sass/_variables.scss
  css/footer.scss
  css/main.scss
  css/take5.scss
  dev/prototypes/courses/comp-1.html
  dev/prototypes/courses/comp-2.html
  dev/prototypes/courses/css/main.scss
  js/jobs.js
Labels: release :tada:

#696 [Bug fix]: Make forum button visible again
  css/main.scss
Labels: bug

#697 [Release]: Blue toque day hero, forum button fix
  _data/hero.yml
  _includes/heros/hero-bbd-2021.html
  css/main.scss
Labels: bug, enhancement
