Repository gymnasium/gymcms, pull requests merged in 2022-01, with the labels that each got.

#705 [Bug fix]: Quick fix for webinars spacing issue
  css/collections.scss
  css/webinars.scss
Labels: bug, CSS

#706 [Release]: Webinars cosmetic fix
  css/collections.scss
  css/webinars.scss
Labels: release :tada:

#707 Courses evergreen hero
  _data/hero.yml
  _includes/heros/hero-courses-evergreen.html
  css/hero-courses-evergreen.scss
  home/img/hero-courses-evergreen/bg-text-1920w.png
  home/img/hero-courses-evergreen/gym-gang-1280w.png
  home/img/hero-courses-evergreen/gym-gang-720w.png
Labels: enhancement

#708 Update Take 5 page layout
  _layouts/take5-raw.html
  css/take5.scss
Labels: enhancement

#709 [Release]: Courses Evergreen Hero and Take 5 Layout
  _data/hero.yml
  _includes/heros/hero-courses-evergreen.html
  _layouts/take5-raw.html
  css/hero-courses-evergreen.scss
  css/take5.scss
  home/img/hero-courses-evergreen/bg-text-1920w.png
  home/img/hero-courses-evergreen/gym-gang-1280w.png
  home/img/hero-courses-evergreen/gym-gang-720w.png
Labels: release :tada:

#710 Retired course message
  _data/courses/GYM-100.yml
  courses/full/course-list-recent.html
  courses/gym-shorts/course-list-recent.html
  css/main.scss
Labels: enhancement, content, CSS

#711 Update retired course message
  _data/courses/GYM-100.yml
  css/main.scss
Labels: enhancement

#712 [Release]: Display retired course messages
  _data/courses/GYM-100.yml
  courses/full/course-list-recent.html
  courses/gym-shorts/course-list-recent.html
  css/main.scss
Labels: release :tada:

#714 Update registration form styling plus
  css/main.scss
Labels: enhancement

#715 GYM-100 retired message update
  _data/courses/GYM-100.yml
  css/main.scss
Labels: enhancement

#713 GYM-100 retired content cleanup
  hub-pages/web-development/index.html
Labels: content
