Repository gymnasium/gymcms, pull requests merged in 2022-06, with the labels that each got.

#762 [Feature]: Updates privacy policy page path
  _includes/partials/footer.html
  _layouts/test-home.html
  sitemap.xml
  tests/json/privacy.html
Labels: release :tada:

#761 Course announcements update
  _data/courses/GYM-002.yml
  _data/courses/GYM-003.yml
  _data/courses/GYM-005.yml
  _data/courses/GYM-008.yml
  _data/courses/GYM-100.yml
  _data/courses/GYM-101.yml
  _sass/_mixins.scss
  css/main.scss
Labels: content

#767 Add courseware styling
  css/main.scss
Labels: enhancement

#768 [Release]: Courseware style update
  css/main.scss
  dev/index-auth.html
  dev/index.html
  dev/prototypes/courses/version-3/css/main.scss
  dev/prototypes/courses/version-3/index.html
  dev/prototypes/courses/version-3/js/main.js
  dev/prototypes/courses/version-4/css/main.scss
  dev/prototypes/courses/version-4/index.html
  dev/prototypes/courses/version-4/js/main.js
Labels: release :tada:
