Repository gymnasium/gymcms, pull requests merged in 2022-05, with the labels that each got.

#750 [Release]: Update courseware code styling
  css/main.scss
Labels: release :tada:

#752 [Release]: Accessibility evergreen hero and static/hub page updates
  _data/hero.yml
  _includes/heros/hero-accessibility.html
  css/hero-accessibility.scss
  hub-pages/remote-work/index.html
  jobs/index.html
  static-pages/social-impact/index.html
Labels: release :tada:

#753 Hide Axure and Sketch
  _data/courses/GYM-005.yml
  _data/courses/GYM-008.yml
  _data/courses/GYM-100.yml
  _includes/take5/recommended-content.html
  hub-pages/prototyping/index.html
  hub-pages/ux-design/index.html
Labels: enhancement

#756 Update retired course assets
  courses/full/GYM-100/announcement.html
  courses/gym-shorts/GYM-005/announcement.html
  courses/gym-shorts/GYM-008/announcement.html
  img/social/courses/gym-005-social.png
  img/social/courses/gym-008-social.png
  img/social/courses/gym-100-social.png
Labels: enhancement

#757 Update retired courses announcement
  _data/courses/GYM-005.yml
  _data/courses/GYM-008.yml
  courses/full/GYM-100/announcement.html
  courses/gym-shorts/GYM-005/announcement.html
  courses/gym-shorts/GYM-008/announcement.html
Labels: enhancement

#759 [Release]: Add course announcements
  _data/courses/GYM-005.yml
  _data/courses/GYM-008.yml
  _data/courses/GYM-100.yml
  courses/full/GYM-100/announcement.html
  courses/full/GYM-102/announcement.html
  courses/full/GYM-103/announcement.html
  courses/full/GYM-104/announcement.html
  courses/full/GYM-106/announcement.html
  courses/full/GYM-107/announcement.html
  courses/full/GYM-108/announcement.html
  courses/full/GYM-109/announcement.html
  courses/gym-shorts/GYM-001/announcement.html
  courses/gym-shorts/GYM-004/announcement.html
  courses/gym-shorts/GYM-005/announcement.html
  courses/gym-shorts/GYM-006/announcement.html
  courses/gym-shorts/GYM-007/announcement.html
  courses/gym-shorts/GYM-008/announcement.html
  courses/gym-shorts/GYM-009/announcement.html
  courses/gym-shorts/GYM-011/announcement.html
  courses/gym-shorts/GYM-012/announcement.html
  courses/gym-shorts/GYM-013/announcement.html
  courses/gym-shorts/GYM-014/announcement.html
  courses/gym-shorts/GYM-015/announcement.html
  courses/gym-shorts/GYM-016/announcement.html
  courses/gym-shorts/GYM-017/announcement.html
  courses/gym-shorts/GYM-018/announcement.html
  courses/gym-shorts/GYM-019/announcement.html
  courses/gym-shorts/GYM-020/announcement.html
  courses/workshops/GYM-700/announcement.html
  css/main.scss
  img/social/courses/gym-005-social.png
  img/social/courses/gym-008-social.png
  img/social/courses/gym-100-social.png
Labels: release :tada:

#758 Add courses metadata
  _data/bios/jhargrove.yml
  _data/courses/GYM-002.yml
  _data/courses/GYM-003.yml
  _data/courses/GYM-101.yml
  _data/courses/GYM-102.yml
  _data/courses/GYM-103.yml
  _data/courses/GYM-104.yml
  _data/courses/GYM-105.yml
  _data/courses/GYM-106.yml
  _data/courses/GYM-107.yml
  _data/courses/GYM-108.yml
  courses/full/GYM-101/announcement.html
  courses/full/GYM-101/meta.md
  courses/full/GYM-105/announcement.html
  courses/full/GYM-105/meta.md
  courses/gym-shorts/GYM-002/announcement.html
  courses/gym-shorts/GYM-002/meta.md
  courses/gym-shorts/GYM-003/announcement.html
  courses/gym-shorts/GYM-003/meta.md
  img/social/courses/gym-002-social.png
  img/social/courses/gym-003-social.png
  img/social/courses/gym-101-social.png
  img/social/courses/gym-105-social.png
  img/webinar-bio-headshots/bio-jason-hargrove.jpg
Labels: content
