Repository gymnasium/gymcms, pull requests merged in 2022-03, with the labels that each got.

#724 Update salary guide artwork
  hub-pages/remote-work/index.html
  img/hub-pages/remote-work/featured/vt-salary-guide-2021.jpg
  img/hub-pages/remote-work/featured/vt-salary-guide-2022.jpg
  jobs/index.html
Labels: content

#725 Update evergreen heros
  _includes/heros/hero-courses-evergreen.html
  _includes/heros/hero-take5-campaign.html
  css/hero-courses-evergreen.scss
  css/hero-take5-campaign.scss
Labels: enhancement

#728 [Patch]: make redirect countdown more flexible
  js/gymnasium.js
Labels: enhancement

#729 Update GYM-100 short description
  _data/courses/GYM-100.yml
  img/social/courses/gym-100-social.png
Labels: enhancement

#731 Update brand logo and OG to support Ukraine
  img/brand/og/gym-brand-og.png
  img/brand/png/gymnasium-logo-white-4x.png
  img/brand/svg/gymnasium-logo-white.svg
Labels: enhancement

#732 Support Ukraine and GYM-100 Retirement
  _data/courses/GYM-100.yml
  img/brand/og/gym-brand-og.png
  img/brand/png/gymnasium-logo-white-4x.png
  img/brand/svg/gymnasium-logo-white.svg
  img/social/courses/gym-100-social.png
Labels: enhancement

#734 [Release]: 🇺🇦 Ukraine Relief hero
  _data/hero.yml
  _includes/heros/hero-ukraine-relief.html
  css/hero-ukraine-relief.scss
  home/img/hero-ukraine-relief/andriyko-podilnyk-TaWaGbjp60Q-unsplash-1280w.jpg
  home/img/hero-ukraine-relief/andriyko-podilnyk-TaWaGbjp60Q-unsplash-1920w.jpg
Labels: release :tada:
